language: node_js
node_js: node
sudo: required
services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-simple"
  env: "Dockersimple-env"
  bucket-name: "simple-docker-bucket"
  bucket-path: "docker"
  on:
    branch: master
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"